export const products = [
  {
    title: "Kit de Soldadura Profesional",
    description: "Estación de soldadura con temperatura regulable, incluye puntas intercambiables y accesorios.",
    price: 89,
    originalPrice: 120,
    rating: 4.8,
    stock: "Disponible",
    category: "Soldadura",
  },
  {
    title: "Set de Herramientas Precisión",
    description: "Kit completo con destornilladores de precisión, pinzas y herramientas para electrónica.",
    price: 45,
    originalPrice: 65,
    rating: 4.9,
    stock: "Disponible",
    category: "Herramientas",
  },
  {
    title: "Multímetro Digital Avanzado",
    description: "Multímetro profesional con pantalla LCD, medición de capacitancia y frecuencia.",
    price: 75,
    originalPrice: 95,
    rating: 4.7,
    stock: "Pocas unidades",
    category: "Medición",
  },
  {
    title: "Kit Arduino Starter",
    description: "Kit completo para iniciarse en Arduino con sensores, LEDs, resistencias y breadboard.",
    price: 55,
    originalPrice: 70,
    rating: 4.9,
    stock: "Disponible",
    category: "Electrónica",
  },
  {
    title: "Pasta Térmica Premium",
    description: "Pasta térmica de alta conductividad para procesadores y componentes electrónicos.",
    price: 15,
    originalPrice: 20,
    rating: 4.6,
    stock: "Disponible",
    category: "Accesorios",
  },
  {
    title: "Pistola de Calor Industrial",
    description: "Pistola de calor con control de temperatura para trabajos de soldadura y reparación.",
    price: 125,
    originalPrice: 150,
    rating: 4.8,
    stock: "Disponible",
    category: "Soldadura",
  },
]; 